name: "Update API docs"

on:
    - push

jobs:
    prepare:
        name: Prepare 
        runs-on: ubuntu-latest
        container:
            image: barichello/godot-ci:3.3 
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                token: ${{ secrets.DEPLOYMENT_TOKEN }}
            - name: Create fake project
              run: |
                touch theme.tres
                godot --path . -e --no-window 
                godot --path . -e --no-window 
            - name: Remove existing docs
              run: |
                rm -rf docs/api
    update:
        name: Update
        needs: prepare
        runs-on: ubuntu-latest
        container:
            image: gdquest/gdscript-docs-maker:1
        steps:
            - name: "Update docs"
              run: |
                cd /app
                ./generate_reference /github/workspace -o /github/workspace/api/docs -d addons/egoventure
            - name: Commit changes
              run: |
                 git status
               
