name: "Update API docs"

on:
    - push

concurrency: api-${{ github.ref }}

jobs:
    update:
        if: "${{ github.event.head_commit.message != 'docs: Automatic update of API docs' }}"
        name: Update
        runs-on: ubuntu-latest
        container:
            image: barichello/godot-ci:3.3 
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                token: ${{ secrets.DEPLOYMENT_TOKEN }}
            - name: Download required addons
              run: |
                echo "Installing curl..."
                apt update && apt install -y curl
                for URL in $(cat .godot-req-addons.txt)
                do
                  echo "Installing addon from ${URL}"
                  curl -L -s -o addon.zip ${URL}
                  unzip -d tmp-addon addon.zip
                  rm addon.zip
                  mv tmp-addon/*/addons/* addons
                  rm -rf tmp-addon
                done
            - name: Create fake project
              run: |
                echo "Removing contrib folder of parrot"
                rm -rf addons/parrot/contrib
                echo "Scanning global objects"
                godot -e --no-window
                cat project.godot
                echo "Faking theme.tres"
                touch theme.tres
                echo "Enabling plugins"
                godot -e --no-window
            - name: Remove existing docs
              run: |
                rm -rf docs/api
                rm theme.tres
                rm first_run.txt
            - name: "Update docs"
              uses: docker://gdquest/gdscript-docs-maker:1
              with:
                entrypoint: "bash"
                args: "-c \"cd /app && ./generate_reference /github/workspace -o /github/workspace/docs/api -d addons/egoventure\""
            - name: "Cleanup"
              run: |
                echo "Cleaning up..."
                rm -rf addons/parrot
                rm -rf addons/speedy_gonzales
            - name: "Commit"
              uses: EndBug/add-and-commit@v7.2.1
              with:
                add: "docs/api"
                message: 'docs: Automatic update of API docs'
                push: true

               
